/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Book`;

CREATE TABLE `Book` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `issn` BIGINT UNSIGNED NOT NULL,
  `isbn` BIGINT UNSIGNED NOT NULL,
  `ChineseCategoryBig` TINYINT UNSIGNED NOT NULL,
  `ChineseCategorySpecific` SMALLINT UNSIGNED NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `id_i`
  ON `Book` (`id`);

CREATE INDEX `issn_i`
  ON `Book` (`issn`);

CREATE INDEX `isbn_i`
  ON `Book` (`isbn`);

CREATE INDEX `ChineseCategoryBig_i`
  ON `Book` (`ChineseCategoryBig`);

CREATE INDEX `ChineseCategorySpecific_i`
  ON `Book` (`ChineseCategorySpecific`);

