/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `dbBook`;

CREATE TABLE `dbBook` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `issn` BIGINT UNSIGNED NOT NULL,
  `isbn` BIGINT UNSIGNED NOT NULL,
  `chinese_category_big` TINYINT UNSIGNED NOT NULL,
  `chinese_category_specific` SMALLINT UNSIGNED NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `id_i`
  ON `dbBook` (`id`);

CREATE INDEX `issn_i`
  ON `dbBook` (`issn`);

CREATE INDEX `isbn_i`
  ON `dbBook` (`isbn`);

CREATE INDEX `chinese_category_big_i`
  ON `dbBook` (`chinese_category_big`);

CREATE INDEX `chinese_category_specific_i`
  ON `dbBook` (`chinese_category_specific`);

